### ISSUE TITLE
Plex dont find it

### ISSUE THREAD

**Issue by Oggymator** [TheJF/antennas#23]
Hi,

Plex dont find it.
Maybe we have to change the name like in this case?
https://github.com/tombowditch/telly/pull/48

regards
Oggymator

**Comment by behinddesign** [comment]
Similar issue. If your case is like mine then you'll need to use host networking on docker and not bridge. You will then see device.xml being requested (see docker logs). Without this the SSDP packets never get handled properly and Plex doesn't know the device is 'alive'.

**Comment by etheralm** [comment]
I have both plex and antennas running in host network mode and it did work up until a month ago when after a plex server server update it stopped being able to find the tuner at all, so not sure if switching to host will help.

**Comment by behinddesign** [comment]
After writing the above I had a few issues. Even after adding the device I could not edit channels shortly after - showing the can't find device message in the DVR settings.

I tinkered around with this a little on my fork https://github.com/behinddesign/antennas (behinddesign/antennas) for the docker image.

With this, I've adjusted the device.xml to output a valid UUID and change the location of the connectionmanager, which to me seemed to be missing the .xml extension (However I didn't see logs of it ever being called)

Things to note:
1) If you can't find the device, restart plex and don't leave any time attempting to add the device, in failing that manually specify the IP and port of antennas
2) **Immediately after adding the dvr device to plex, restart plex**. This will cause the device not found error to go away. On my version it doesn't appear to ever show the device not found error when editing channels. With this original version it would break after a certain amount of time or almost immediately, there appear to be no rhyme or reason to this.
3) You may have to delete and re-add your device if you test my fork to see if the changes fix it for you. I suspect the valid UUID (UDN) is the cause?

YMMV, Hopefully TheJF will be able to shed more light on this.

**Comment by etheralm** [comment]
thank you, I tried you docker image today but plex still couldn't find the antennas dvr even when entering the ip/hostname manually. I'll try to run both on seperate physical hosts over the weekend and see if I can get it to work that way.

**Comment by Oggymator** [comment]
At the moment I tried Antennas und Telly(Plex DVR for IPTV).
Telly works at the moment a bit better, I think one reason could be the name. Possible to change in antennas dockers?

But for both I have the problem, Plex find it, I click on it and it is dead.

I run Antennas and Telly in Docker.
Plex on an other Windows VM.

**Comment by behinddesign** [comment]
Then I have a feeling that our issues aren't related. In any case the fix will, once you do manage to get it working should make it work better.

On my pull request I've adjusted the name and you can test this docker image : behinddesign/antennas until TheJF reviews the pull request or comes back with something better.

**Comment by TheJF** [comment]
Thanks for the PR @behinddesign ! I looked at it and it looks very solid. I'll give it a whirl tonight or early tomorrow for testing's sake, but pretty sure that it'll work out of the box and won't need changes, and I'll merge it in if there's no problem.

**Comment by Oggymator** [comment]
hm, I played a bit with it and it seems working now. don't know what was the problem first :(
changed also from bridge to host.

at the moment I could finish the settings for DVR the first time, now I have to wait for EPG data.

**Comment by behinddesign** [comment]
I have found the web interface viewing for plex to be very flakey with DVR. I use a firestick and Plex Media Center (on Windows and Mac) and they all work fine.

If TVH shows that the stream is running and the webinterface continues to 'load', this is a sign that it is working, but not via the web interface, at least for me.

**Comment by Oggymator** [comment]
Docker is no more working, with your changes:

`Broadcasting to SSDP for discovery...

events.js:165

      throw er; // Unhandled 'error' event

      ^


Error: listen EADDRINUSE :::5004

    at Server.setupListenHandle [as _listen2] (net.js:1346:14)

    at listenInCluster (net.js:1387:12)

    at Server.listen (net.js:1475:7)

    at Application.listen (/antennas/node_modules/koa/lib/application.js:64:19)

    at Object.<anonymous> (/antennas/index.js:27:7)

    at Module._compile (internal/modules/cjs/loader.js:654:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)

    at Module.load (internal/modules/cjs/loader.js:566:32)

    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)

    at Function.Module._load (internal/modules/cjs/loader.js:498:3)

    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)

    at startup (internal/bootstrap/node.js:201:19)

    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)

Emitted 'error' event at:

    at emitErrorNT (net.js:1366:8)

    at process._tickCallback (internal/process/next_tick.js:178:19)

    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)

    at startup (internal/bootstrap/node.js:201:19)

    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)`

**Comment by TheJF** [comment]
@Oggymator What is the docker command you've used to run this?

Because it works for me like this:
<img width="1112" alt="screen shot 2018-06-16 at 10 48 23 am" src="https://user-images.githubusercontent.com/999846/41501118-f4d8462a-7152-11e8-88e1-6c755fdbb643.png">

**Comment by Oggymator** [comment]
I used;
`sudo docker run -p 5004:5004 --network host - e ANTENNAS_URL=http://xxx.xxx.xxx.xxx:5004 -e TVHEADEND_URL=http://test:test@xxx.xxx.xxx.xxx:9981 thejf/antennas`

**Comment by TheJF** [comment]
Personally, I never got it to work using `--net=host` or `--network host`

What seems to be happening in your case is that you have another server (another Antennas, or maybe Telly?) that's running on port 5004 (that's what they mean by Error: listen EADDRINUSE :::5004, which, isn't very clear English :P) Ports can only be used by one thing at a time, so if something else is already using it, it'll cause an error for anything else that tries to use it. 

So this is why in your case your Antennas server isn't working, because there's already something else using port 5004. If you get rid of the other thing, then it should work.

**Comment by Oggymator** [comment]
damn, you are right.
there was a docker with cowries names, so I never thought that could be antennas.
Now it works again.

But I could not solve the problem, that now stream is starting.
I used it on Web App and iOS and tvOS device.
TVH client works well.
